import { Router } from "express";
import { GenerateCiscoConfigBody } from "@workspace/api-zod";

const router = Router();

router.post("/generate-config", async (req, res) => {
  const parsed = GenerateCiscoConfigBody.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: parsed.error.message });

  const {
    radiusServerIp,
    radiusSecret,
    radiusAuthPort = 1812,
    radiusAcctPort = 1813,
    guestVlanId = 100,
    quarantineVlanId = 999,
    reauthTimer = 3600,
    enableDot1x = true,
    enableMab = true,
    interfaces = [],
  } = parsed.data;

  const warnings: string[] = [];

  let config = `! ============================================================
! Network Access Control - Cisco Catalyst 2960X Configuration
! Generated by NAC Manager
! Generated: ${new Date().toISOString()}
! ============================================================

! ─────────────────────────────
! AAA Configuration
! ─────────────────────────────
aaa new-model
aaa authentication dot1x default group radius
aaa authorization network default group radius
aaa accounting dot1x default start-stop group radius

! ─────────────────────────────
! RADIUS Server Configuration
! ─────────────────────────────
radius server NAC-SERVER
 address ipv4 ${radiusServerIp} auth-port ${radiusAuthPort} acct-port ${radiusAcctPort}
 key ${radiusSecret}
 timeout 5
 retransmit 3

! ─────────────────────────────
! 802.1X Global Configuration
! ─────────────────────────────
`;

  if (enableDot1x) {
    config += `dot1x system-auth-control\n`;
  }

  config += `
! ─────────────────────────────
! VLAN Configuration
! ─────────────────────────────
vlan ${guestVlanId}
 name GUEST-VLAN
!
vlan ${quarantineVlanId}
 name QUARANTINE-VLAN
!

! ─────────────────────────────
! Interface Configuration
! ─────────────────────────────
`;

  const ifaces = interfaces.length > 0 ? interfaces : ["GigabitEthernet0/1"];
  if (interfaces.length === 0) {
    warnings.push("No interfaces specified. Example configuration shown for GigabitEthernet0/1.");
  }

  for (const iface of ifaces) {
    config += `interface ${iface}
 switchport mode access
 switchport access vlan 1`;

    if (enableDot1x) {
      config += `
 dot1x pae authenticator
 dot1x timeout quiet-period 30
 dot1x timeout tx-period 10
 dot1x max-reauth-req 3
 dot1x reauthentication
 dot1x timeout reauth-period ${reauthTimer}`;
    }

    if (enableMab) {
      config += `
 mab`;
    }

    config += `
 authentication event fail action authorize vlan ${quarantineVlanId}
 authentication event no-response action authorize vlan ${guestVlanId}
 authentication host-mode multi-auth
 authentication order`;

    if (enableDot1x) config += ` dot1x`;
    if (enableMab) config += ` mab`;

    config += `
 authentication priority`;
    if (enableDot1x) config += ` dot1x`;
    if (enableMab) config += ` mab`;

    config += `
 authentication port-control auto
 spanning-tree portfast
!
`;
  }

  config += `
! ─────────────────────────────
! SNMP Traps (Optional)
! ─────────────────────────────
snmp-server enable traps dot1x
snmp-server enable traps mac-notification

! ─────────────────────────────
! End of Configuration
! ─────────────────────────────
end
`;

  res.json({ config, warnings });
});

export default router;
